In [40]:
# import mysql.connector

In [41]:
# import seaborn as sns

In [42]:
# import mysql.connector

In [43]:
# import mysql.connector
# import mysql.connector

In [44]:
# import mysql.connector

In [45]:
# import mysql.connector

In [46]:
# import sys
# !{sys.executable} -m pip install mysql-connector-pytho

In [47]:
#import sys
#!{sys.executable} -m pip install mysql-connector-python

# import sys
# !{sys.executable} -m pip install pandas

In [2]:
pip install python-dotenv

Collecting python-dotenv
  Using cached python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Using cached python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.2
Note: you may need to restart the kernel to use updated packages.

In [48]:
#import mysql.connector
from mysql import connector
from dotenv import load_dotenv
import pandas as pd

In [49]:
import os
load_dotenv()

user= os.getenv("USER")
password= os.getenv('PASSWORD')
host= os.getenv("HOST")

database="swiftmarket"

In [51]:
connection=connector.connect(
    user= user,
    password= password,
    host= host,
    database= database

)
cursor = connection.cursor()

In [52]:
connection.is_connected()

True

In [53]:
query ='''show tables'''
cursor.execute(query)
rows = cursor.fetchall()
for row in rows:
    print(row)

('categories',)
('customers',)
('employees',)
('salesdata',)
('subcategories',)
('suppliers',)

In [54]:
# dimension tables: all tables containing primary keys and connected to fact table
# fact table: e.g sales data

query= '''select *from salesdata limit 5'''
cursor.execute(query)
rows = cursor.fetchall()
for row in rows:
    print(row)

(23000, 'C-2023-100-12', 6002, 1100, datetime.date(2023, 5, 2), 2, Decimal('176432.00'))
(23001, 'C-2023-100-141', 6029, 1115, datetime.date(2023, 12, 26), 2, Decimal('47172.00'))
(23002, 'C-2023-100-86', 6029, 1035, datetime.date(2023, 3, 26), 2, Decimal('47172.00'))
(23003, 'C-2023-100-72', 6006, 1016, datetime.date(2023, 8, 1), 2, Decimal('117644.00'))
(23004, 'C-2023-100-142', 6030, 1067, datetime.date(2023, 3, 6), 5, Decimal('336560.00'))

In [56]:
cursor.column_names

('SaleID',
 'CustomerID',
 'SubcatID',
 'EmployeeID',
 'SaleDate',
 'Quantity',
 'TotalPrice')

In [57]:
pd.DataFrame(data= rows, columns=cursor.column_names)

,SaleID,CustomerID,SubcatID,EmployeeID,SaleDate,Quantity,TotalPrice
0,23000,C-2023-100-12,6002,1100,2023-05-02,2,176432.00
1,23001,C-2023-100-141,6029,1115,2023-12-26,2,47172.00
2,23002,C-2023-100-86,6029,1035,2023-03-26,2,47172.00
3,23003,C-2023-100-72,6006,1016,2023-08-01,2,117644.00
4,23004,C-2023-100-142,6030,1067,2023-03-06,5,336560.00

In [63]:
def fetch_salesdata(cursor):
    query = '''SELECT * FROM salesdata LIMIT 5'''
    cursor.execute(query)
    read_query = cursor.fetchall()
    return read_query



read_query = fetch_salesdata(cursor)

for row in read_query:
    print(read_query)

[(23000, 'C-2023-100-12', 6002, 1100, datetime.date(2023, 5, 2), 2, Decimal('176432.00')), (23001, 'C-2023-100-141', 6029, 1115, datetime.date(2023, 12, 26), 2, Decimal('47172.00')), (23002, 'C-2023-100-86', 6029, 1035, datetime.date(2023, 3, 26), 2, Decimal('47172.00')), (23003, 'C-2023-100-72', 6006, 1016, datetime.date(2023, 8, 1), 2, Decimal('117644.00')), (23004, 'C-2023-100-142', 6030, 1067, datetime.date(2023, 3, 6), 5, Decimal('336560.00'))]
[(23000, 'C-2023-100-12', 6002, 1100, datetime.date(2023, 5, 2), 2, Decimal('176432.00')), (23001, 'C-2023-100-141', 6029, 1115, datetime.date(2023, 12, 26), 2, Decimal('47172.00')), (23002, 'C-2023-100-86', 6029, 1035, datetime.date(2023, 3, 26), 2, Decimal('47172.00')), (23003, 'C-2023-100-72', 6006, 1016, datetime.date(2023, 8, 1), 2, Decimal('117644.00')), (23004, 'C-2023-100-142', 6030, 1067, datetime.date(2023, 3, 6), 5, Decimal('336560.00'))]
[(23000, 'C-2023-100-12', 6002, 1100, datetime.date(2023, 5, 2), 2, Decimal('176432.00')), (23001, 'C-2023-100-141', 6029, 1115, datetime.date(2023, 12, 26), 2, Decimal('47172.00')), (23002, 'C-2023-100-86', 6029, 1035, datetime.date(2023, 3, 26), 2, Decimal('47172.00')), (23003, 'C-2023-100-72', 6006, 1016, datetime.date(2023, 8, 1), 2, Decimal('117644.00')), (23004, 'C-2023-100-142', 6030, 1067, datetime.date(2023, 3, 6), 5, Decimal('336560.00'))]
[(23000, 'C-2023-100-12', 6002, 1100, datetime.date(2023, 5, 2), 2, Decimal('176432.00')), (23001, 'C-2023-100-141', 6029, 1115, datetime.date(2023, 12, 26), 2, Decimal('47172.00')), (23002, 'C-2023-100-86', 6029, 1035, datetime.date(2023, 3, 26), 2, Decimal('47172.00')), (23003, 'C-2023-100-72', 6006, 1016, datetime.date(2023, 8, 1), 2, Decimal('117644.00')), (23004, 'C-2023-100-142', 6030, 1067, datetime.date(2023, 3, 6), 5, Decimal('336560.00'))]
[(23000, 'C-2023-100-12', 6002, 1100, datetime.date(2023, 5, 2), 2, Decimal('176432.00')), (23001, 'C-2023-100-141', 6029, 1115, datetime.date(2023, 12, 26), 2, Decimal('47172.00')), (23002, 'C-2023-100-86', 6029, 1035, datetime.date(2023, 3, 26), 2, Decimal('47172.00')), (23003, 'C-2023-100-72', 6006, 1016, datetime.date(2023, 8, 1), 2, Decimal('117644.00')), (23004, 'C-2023-100-142', 6030, 1067, datetime.date(2023, 3, 6), 5, Decimal('336560.00'))]

In [68]:
def read_query(query):
    cursor.execute(query)
    rows=cursor.fetchall()
    return pd.DataFrame(data=rows,columns=cursor.column_names)

In [69]:
query='''select *from customers limit 5'''
read_query(query)

,CustomerID,FirstName,LastName,Email,Phone,Address,State
0,C-2023-100-1,Mahika,Sunder,MahikaSunder_11@zmail.com,03412176590,"H.No. 155, Chana",Assam
1,C-2023-100-10,Zeeshan,Vasa,ZeeshanVasa_1@zmail.com,+911151051656,"52, Roy Nagar",Tripura
2,C-2023-100-100,Aaina,Sachdeva,AainaSachdeva_9@zmail.com,+918834507719,"75/92, Kade Marg",Nagaland
3,C-2023-100-101,Shray,Bajwa,ShrayBajwa_11@zmail.com,07410498662,"45, Bora Ganj",Manipur
4,C-2023-100-102,Navya,Dash,NavyaDash_5@zmail.com,+917644200850,70/782\nBahl Road,Kerala

In [74]:
query='''select s.saledate, c.firstname, s.totalprice
from salesdata as s
inner join customers as c on
c.Customerid = s.customerid
order by s.totalprice
limit 10'''

read_query(query)

     saledate firstname totalprice
0  2023-05-26   Vritika    1726.00
1  2023-04-18     Seher    1726.00
2  2023-06-23    Damini    1726.00
3  2023-09-01   Manikya    1726.00
4  2023-05-09  Divyansh    1726.00
5  2023-11-28     Taran    1726.00
6  2023-10-14     Shray    1726.00
7  2023-04-05   Inaaya     1726.00
8  2023-04-18   Vaibhav    1726.00
9  2023-09-24     Shalv    1726.00